// 1000_Mots_Anglais — données
// Prononciation : General American
// W : [mot, API, traduction, remarque, rang de fréquence]
// G : [nom du groupe, nombre de mots] — les mots de W sont rangés dans cet ordre
var W = [
["to", "tu", "à", "atone : /tə/ devant consonne, /tu/ devant voyelle", 2],
["of", "ʌv", "de", "atone : /əv/", 4],
["in", "ɪn", "dans", "", 6],
["for", "fɔɹ", "pour", "atone : /fɚ/", 9],
["on", "ɑn", "sur", "", 13],
["with", "wɪð", "avec", "", 14],
["at", "æt", "à", "atone : /ət/", 21],
["by", "baɪ", "par", "", 24],
["from", "fɹʌm", "de", "atone : /fɹəm/", 26],
["about", "əˈbaʊt", "à propos de", "", 43],
["after", "ˈæftɚ", "après", "", 80],
["into", "ˈɪntu", "dans", "", 83],
["over", "ˈoʊvɚ", "au-dessus", "", 88],
["before", "bɪˈfɔɹ", "avant", "", 121],
["through", "θɹu", "à travers", "", 136],
["around", "ɚˈaʊnd", "autour", "", 160],
["between", "bɪˈtwin", "entre", "", 161],
["since", "sɪns", "depuis", "", 169],
["under", "ˈʌndɚ", "sous", "", 174],
["during", "ˈdʊɹɪŋ", "pendant", "", 175],
["without", "wɪˈθaʊt", "sans", "", 186],
["against", "əˈɡɛnst", "contre", "", 187],
["until", "ənˈtɪl", "jusqu'à", "", 216],
["including", "ˌɪnˈkludɪŋ", "y compris", "", 269],
["per", "pɝ", "par", "", 328],
["within", "wɪˈðɪn", "à l'intérieur de", "", 340],
["along", "əˈlɔŋ", "le long de", "", 396],
["among", "əˈmʌŋ", "parmi", "", 469],
["behind", "bɪˈhaɪnd", "derrière", "", 491],
["near", "nɪɹ", "près de", "", 496],
["according", "əˈkɔɹdɪŋ", "according to : selon", "", 504],
["across", "əˈkɹɔs", "à travers", "", 536],
["above", "əˈbʌv", "au-dessus", "", 603],
["upon", "əˈpɑn", "sur", "", 762],
["towards", "təˈwɔɹdz", "vers", "", 897],
["below", "bɪˈloʊ", "en dessous", "", 903],
["except", "ɪkˈsɛpt", "sauf", "", 973],
["via", "ˈvaɪə", "via", "", 989],
["the", "ðʌ", "le", "atone : /ðə/ devant consonne, /ði/ devant voyelle", 1],
["a", "eɪ", "un", "atone : /ə/", 5],
["I", "aɪ", "je", "", 7],
["you", "ju", "tu", "atone : /jə/", 11],
["it", "ɪt", "il", "", 12],
["this", "ðɪs", "ceci", "", 15],
["he", "hi", "il", "atone : /i/, h muet", 22],
["we", "wi", "nous", "", 29],
["an", "æn", "un", "atone : /ən/", 30],
["they", "ðeɪ", "ils", "", 35],
["me", "mi", "moi", "", 36],
["what", "wʌt", "quoi", "", 46],
["who", "hu", "qui", "", 53],
["her", "hɝ", "elle", "atone : /ɚ/, h muet", 58],
["which", "wɪtʃ", "lequel", "", 59],
["she", "ʃi", "elle", "", 64],
["them", "ðɛm", "eux", "atone : /ðəm/, /əm/", 71],
["him", "hɪm", "lui", "atone : /ɪm/, h muet", 82],
["these", "ðiz", "ces", "", 94],
["us", "ʌs", "nous", "atone : /əs/", 95],
["those", "ðoʊz", "ceux-là", "", 130],
["something", "ˈsʌmθɪŋ", "quelque chose", "", 148],
["someone", "ˈsʌmˌwʌn", "quelqu'un", "", 206],
["anything", "ˈɛniˌθɪŋ", "quoi que ce soit", "", 245],
["nothing", "ˈnʌθɪŋ", "rien", "", 247],
["everything", "ˈɛvɹiˌθɪŋ", "tout", "", 252],
["everyone", "ˈɛvɹiˌwʌn", "tout le monde", "", 309],
["others", "ˈʌðɚz", "les autres", "", 354],
["anyone", "ˈɛniˌwʌn", "n'importe qui", "", 397],
["either", "ˈiðɚ", "l'un ou l'autre", "", 447],
["myself", "ˌmaɪˈsɛlf", "moi-même", "", 476],
["yourself", "jɚˈsɛlf", "toi-même", "", 478],
["himself", "hɪmˈsɛlf", "lui-même", "", 541],
["themselves", "ðɛmˈsɛlvz", "eux-mêmes", "", 692],
["whatever", "ˌwʌˈtɛvɚ", "peu importe", "", 726],
["itself", "ˌɪtˈsɛlf", "lui-même", "", 793],
["ones", "wʌnz", "ceux", "", 871],
["whose", "huz", "dont", "", 881],
["mine", "maɪn", "le mien", "", 929],
["it's", "ɪts", "c'est (it is / it has)", "it is / it has", 55],
["don't", "doʊnt", "ne … pas (do not)", "do not", 68],
["I'm", "aɪm", "je suis (I am)", "I am", 74],
["you're", "jʊɹ", "tu es", "you are", 137],
["that's", "ðæts", "c'est", "that is", 139],
["can't", "kænt", "ne peut pas (cannot)", "cannot", 150],
["I've", "aɪv", "j'ai (I have)", "I have", 177],
["didn't", "ˈdɪdənt", "n'a pas (did not)", "did not", 188],
["he's", "hiz", "il est / il a (he is / he has)", "he is / he has", 220],
["there's", "ðɛɹz", "il y a (there is)", "there is", 258],
["doesn't", "ˈdʌzənt", "ne … pas (does not)", "does not", 262],
["they're", "ðɛɹ", "ils sont (they are)", "they are", 311],
["I'll", "aɪl", "je vais", "I will", 345],
["oh", "oʊ", "oh", "", 348],
["thanks", "θæŋks", "merci", "", 350],
["isn't", "ˈɪzənt", "n'est pas (is not)", "is not", 363],
["we're", "wiɹ", "nous sommes (we are)", "we are", 381],
["fuck", "fʌk", "putain (vulg.)", "", 383],
["yeah", "jɛə", "ouais", "", 414],
["I'd", "aɪd", "je voudrais / j'avais (I would / I had)", "I would / I had", 419],
["won't", "woʊnt", "ne … pas (futur", "will not", 446],
["gonna", "ˈɡɑnə", "aller", "going to (familier)", 494],
["wasn't", "ˈwɑzənt", "n'était pas (was not)", "was not", 516],
["she's", "ʃiz", "elle est / elle a (she is / she has)", "she is / she has", 532],
["you'll", "jul", "tu vas", "you will", 591],
["what's", "wʌts", "qu'est-ce que (what is)", "what is", 617],
["wouldn't", "ˈwʊdənt", "ne … pas (conditionnel", "would not", 656],
["let's", "lɛts", "allons", "let us", 681],
["you've", "juv", "tu as", "you have", 747],
["hey", "heɪ", "hé", "", 753],
["haven't", "ˈhævənt", "n'ai pas", "have not", 772],
["couldn't", "ˈkʊdənt", "ne pouvait pas (could not)", "could not", 807],
["damn", "dæm", "zut", "", 808],
["okay", "ˌoʊˈkeɪ", "d'accord", "aussi écrit ok", 891],
["aren't", "ˈɑɹənt", "ne sont pas (are not)", "are not", 901],
["wanna", "ˈwɑnə", "vouloir", "want to (familier)", 940],
["we've", "wiv", "nous avons (we have)", "we have", 941],
["and", "ænd", "et", "atone : /ən/, /n̩/", 3],
["that", "ðæt", "que", "atone : /ðət/ comme conjonction ; /ðæt/ comme démonstratif", 10],
["as", "æz", "comme", "atone : /əz/", 18],
["but", "bʌt", "mais", "atone : /bət/", 25],
["my", "maɪ", "mon", "", 27],
["or", "ɔɹ", "ou", "atone : /ɚ/", 28],
["your", "jɔɹ", "ton", "atone : /jɚ/", 31],
["his", "hɪz", "son", "atone : /ɪz/, h muet", 34],
["if", "ɪf", "si", "", 37],
["one", "wʌn", "un", "", 38],
["can", "kæn", "pouvoir", "atone : /kən/", 39],
["will", "wɪl", "(futur)", "atone : /əl/, /l̩/", 40],
["their", "ðɛɹ", "leur", "atone : /ðɚ/", 56],
["would", "wʊd", "(conditionnel)", "atone : /wəd/, /əd/", 63],
["its", "ɪts", "son", "", 75],
["our", "ˈaʊɚ", "notre", "", 76],
["than", "ðæn", "que", "atone : /ðən/", 77],
["two", "tu", "deux", "", 86],
["could", "kʊd", "pourrait", "atone : /kəd/", 92],
["because", "bɪˈkɔz", "parce que", "", 97],
["should", "ʃʊd", "devrait", "atone : /ʃəd/", 107],
["may", "meɪ", "pouvoir", "", 108],
["while", "waɪl", "pendant que", "", 140],
["three", "θɹi", "trois", "", 159],
["must", "mʌst", "devoir", "atone : /məst/", 191],
["might", "maɪt", "pourrait", "", 200],
["four", "fɔɹ", "quatre", "", 263],
["though", "ðoʊ", "bien que", "", 289],
["five", "faɪv", "cinq", "", 325],
["third", "θɝd", "troisième", "", 466],
["whether", "ˈwɛðɚ", "si", "", 468],
["although", "ˌɔlˈðoʊ", "bien que", "", 480],
["six", "sɪks", "six", "", 500],
["cannot", "ˈkænɑt", "ne peut pas", "", 766],
["seven", "ˈsɛvən", "sept", "", 846],
["ten", "tɛn", "dix", "", 917],
["shall", "ʃæl", "(futur, formel)", "atone : /ʃəl/", 960],
["eight", "eɪt", "huit", "", 972],
["use", "juz", "utiliser", "v. /juz/ · n. /jus/", 149],
["does", "dʌz", "fait", "v. /dʌz/, atone /dəz/ · n. pl. de doe /doʊz/", 171],
["house", "haʊs", "maison", "n. /haʊs/ · v. /haʊz/", 180],
["live", "lɪv", "vivre", "v. /lɪv/ · adj./adv. /laɪv/", 254],
["read", "ɹid", "lire", "présent /ɹid/ · passé et participe /ɹɛd/", 257],
["research", "ˈɹisɚtʃ", "recherche", "n. /ˈɹisɚtʃ/ · v. /ɹɪˈsɝtʃ/", 388],
["close", "kloʊs", "fermer", "adj. /kloʊs/ · v. /kloʊz/", 417],
["project", "ˈpɹɑdʒɛkt", "projet", "n. /ˈpɹɑdʒɛkt/ · v. /pɹəˈdʒɛkt/", 586],
["record", "ˈɹɛkɚd", "enregistrement", "n. /ˈɹɛkɚd/ · v. /ɹɪˈkɔɹd/", 600],
["lead", "lid", "mener", "v. /lid/ · n. plomb /lɛd/", 610],
["perfect", "ˈpɝfɪkt", "parfait", "adj. /ˈpɝfɪkt/ · v. /pɚˈfɛkt/", 613],
["present", "ˈpɹɛzənt", "présent", "n./adj. /ˈpɹɛzənt/ · v. /pɹɪˈzɛnt/", 650],
["lives", "laɪvz", "vies", "n. pl. de life /laɪvz/ · v. /lɪvz/", 716],
["increase", "ɪnˈkɹis", "augmenter", "n. /ˈɪnkɹis/ · v. /ɪnˈkɹis/", 839],
["when", "wɛn", "quand", "", 48],
["get", "ɡɛt", "obtenir", "", 61],
["any", "ˈɛni", "n'importe quel", "", 90],
["then", "ðɛn", "alors", "", 91],
["well", "wɛl", "bien", "", 99],
["said", "sɛd", "dit", "", 100],
["many", "ˈmɛni", "beaucoup de", "", 128],
["never", "ˈnɛvɚ", "jamais", "", 129],
["best", "bɛst", "meilleur", "", 141],
["every", "ˈɛvɚi", "chaque", "", 154],
["better", "ˈbɛtɚ", "meilleur", "", 163],
["help", "hɛlp", "aider", "", 165],
["again", "əˈɡɛn", "encore", "", 183],
["next", "nɛkst", "prochain", "", 184],
["end", "ɛnd", "fin", "", 189],
["ever", "ˈɛvɚ", "jamais", "", 197],
["second", "ˈsɛkənd", "deuxième", "", 205],
["left", "lɛft", "gauche", "", 208],
["let", "lɛt", "laisser", "", 221],
["set", "sɛt", "mettre", "", 226],
["however", "ˌhaʊˈɛvɚ", "cependant", "", 229],
["getting", "ˈɡɛtɪŋ", "obtenant", "", 230],
["already", "ɔlˈɹɛdi", "déjà", "", 244],
["yet", "jɛt", "encore", "", 260],
["tell", "tɛl", "dire", "", 268],
["head", "hɛd", "tête", "", 279],
["men", "mɛn", "hommes", "", 280],
["went", "wɛnt", "est allé", "", 291],
["yes", "jɛs", "oui", "", 292],
["less", "lɛs", "moins", "", 296],
["says", "sɛz", "dit", "", 301],
["general", "ˈdʒɛnɚəl", "général", "", 310],
["together", "təˈɡɛðɚ", "ensemble", "", 320],
["president", "ˈpɹɛzəˌdɛnt", "président", "", 329],
["health", "hɛlθ", "santé", "", 334],
["friends", "fɹɛndz", "amis", "", 344],
["level", "ˈlɛvəl", "niveau", "", 364],
["death", "dɛθ", "mort", "", 372],
["several", "ˈsɛvɹəl", "plusieurs", "", 390],
["else", "ɛls", "d'autre", "", 398],
["remember", "ɹɪˈmɛmbɚ", "se souvenir", "", 403],
["friend", "fɹɛnd", "ami", "", 406],
["members", "ˈmɛmbɚz", "membres", "", 430],
["question", "ˈkwɛstʃən", "question", "", 433],
["special", "ˈspɛʃəl", "spécial", "", 444],
["red", "ɹɛd", "rouge", "", 463],
["check", "tʃɛk", "vérifier", "", 470],
["development", "dɪˈvɛləpmənt", "développement", "", 471],
["west", "wɛst", "ouest", "", 502],
["ready", "ˈɹɛdi", "prêt", "", 512],
["gets", "ɡɛts", "obtient", "", 540],
["self", "sɛlf", "soi", "", 544],
["held", "hɛld", "tenu", "", 551],
["instead", "ˌɪnˈstɛd", "au lieu de", "", 552],
["energy", "ˈɛnɚdʒi", "énergie", "", 562],
["rest", "ɹɛst", "repos", "", 571],
["sex", "sɛks", "sexe", "", 587],
["especially", "əˈspɛʃli", "surtout", "", 593],
["center", "ˈsɛntɚ", "centre", "", 620],
["dead", "dɛd", "mort", "", 623],
["sense", "sɛns", "sens", "", 636],
["test", "tɛst", "test", "", 638],
["event", "ɪˈvɛnt", "événement", "", 644],
["member", "ˈmɛmbɚ", "membre", "", 647],
["guess", "ɡɛs", "deviner", "", 664],
["medical", "ˈmɛdəkəl", "médical", "", 683],
["press", "pɹɛs", "presse", "", 688],
["sent", "sɛnt", "envoyé", "", 691],
["director", "dɚˈɛktɚ", "directeur", "", 701],
["questions", "ˈkwɛstʃənz", "questions", "", 707],
["evidence", "ˈɛvədəns", "preuve", "", 714],
["federal", "ˈfɛdɚəl", "fédéral", "", 735],
["felt", "fɛlt", "ressenti", "", 737],
["step", "stɛp", "pas", "", 745],
["central", "ˈsɛntɹəl", "central", "", 748],
["attention", "əˈtɛnʃən", "attention", "", 764],
["led", "lɛd", "mené", "", 774],
["send", "sɛnd", "envoyer", "", 781],
["hell", "hɛl", "enfer", "", 791],
["met", "mɛt", "rencontré", "", 816],
["website", "ˈwɛbˌsaɪt", "site web", "", 823],
["election", "ɪˈlɛkʃən", "élection", "", 833],
["events", "ɪˈvɛnts", "événements", "", 835],
["bed", "bɛd", "lit", "", 855],
["forget", "fɚˈɡɛt", "oublier", "", 886],
["success", "səkˈsɛs", "succès", "", 896],
["professional", "pɹəˈfɛʃənəl", "professionnel", "", 911],
["percent", "pɚˈsɛnt", "pour cent", "", 932],
["respect", "ɹɪˈspɛkt", "respect", "", 956],
["century", "ˈsɛntʃɚi", "siècle", "", 967],
["effect", "ɪˈfɛkt", "effet", "", 971],
["network", "ˈnɛˌtwɝk", "réseau", "", 978],
["spent", "spɛnt", "dépensé", "", 984],
["ahead", "əˈhɛd", "devant", "", 993],
["make", "meɪk", "faire", "", 87],
["way", "weɪ", "chemin", "", 101],
["day", "deɪ", "jour", "", 118],
["made", "meɪd", "fait", "", 124],
["take", "teɪk", "prendre", "", 126],
["say", "seɪ", "dire", "", 132],
["great", "ɡɹeɪt", "grand", "", 135],
["same", "seɪm", "même", "", 151],
["state", "steɪt", "état", "", 158],
["game", "ɡeɪm", "jeu", "", 176],
["place", "pleɪs", "endroit", "", 181],
["away", "əˈweɪ", "loin", "", 207],
["days", "deɪz", "jours", "", 211],
["name", "neɪm", "nom", "", 213],
["play", "pleɪ", "jouer", "", 215],
["case", "keɪs", "cas", "", 246],
["today", "təˈdeɪ", "aujourd'hui", "", 249],
["change", "tʃeɪndʒ", "changer", "", 250],
["making", "ˈmeɪkɪŋ", "faisant", "", 255],
["states", "steɪts", "États", "", 273],
["based", "beɪst", "basé", "", 276],
["came", "keɪm", "est venu", "", 285],
["later", "ˈleɪtɚ", "plus tard", "", 295],
["makes", "meɪks", "fait", "", 319],
["face", "feɪs", "visage", "", 324],
["maybe", "ˈmeɪbi", "peut-être", "", 327],
["games", "ɡeɪmz", "jeux", "", 333],
["able", "ˈeɪbəl", "capable", "", 341],
["information", "ˌɪnfɚˈmeɪʃən", "information", "", 346],
["pay", "peɪ", "payer", "", 377],
["taking", "ˈteɪkɪŋ", "prenant", "", 392],
["playing", "ˈpleɪɪŋ", "jouant", "", 410],
["saying", "ˈseɪɪŋ", "disant", "", 412],
["wait", "weɪt", "attendre", "", 435],
["data", "ˈdeɪtə", "données", "", 439],
["late", "leɪt", "tard", "", 440],
["stay", "steɪ", "rester", "", 456],
["taken", "ˈteɪkən", "pris", "", 457],
["age", "eɪdʒ", "âge", "", 458],
["major", "ˈmeɪdʒɚ", "majeur", "", 486],
["players", "ˈpleɪɚz", "joueurs", "", 489],
["available", "əˈveɪləbəl", "disponible", "", 505],
["education", "ˌɛdʒəˈkeɪʃən", "éducation", "", 506],
["baby", "ˈbeɪbi", "bébé", "", 527],
["gave", "ɡeɪv", "a donné", "", 539],
["main", "meɪn", "principal", "", 553],
["played", "pleɪd", "joué", "", 568],
["space", "speɪs", "espace", "", 575],
["date", "deɪt", "date", "", 581],
["player", "ˈpleɪɚ", "joueur", "", 631],
["break", "bɹeɪk", "casser", "", 641],
["takes", "teɪks", "prend", "", 653],
["training", "ˈtɹeɪnɪŋ", "formation", "", 654],
["became", "bɪˈkeɪm", "est devenu", "", 697],
["relationship", "ɹiˈleɪʃənˌʃɪp", "relation", "", 708],
["rate", "ɹeɪt", "taux", "", 719],
["save", "seɪv", "sauver", "", 722],
["changes", "ˈtʃeɪndʒəz", "changements", "", 749],
["page", "peɪdʒ", "page", "", 756],
["paid", "peɪd", "payé", "", 757],
["range", "ɹeɪndʒ", "gamme", "", 758],
["trade", "tɹeɪd", "commerce", "", 761],
["hate", "heɪt", "haïr", "", 771],
["amazing", "əˈmeɪzɪŋ", "incroyable", "", 784],
["related", "ɹɪˈleɪtɪd", "lié", "", 798],
["stage", "steɪdʒ", "scène", "", 800],
["situation", "ˌsɪtʃuˈeɪʃən", "situation", "", 820],
["race", "ɹeɪs", "course", "", 844],
["changed", "tʃeɪndʒd", "changé", "", 859],
["crazy", "ˈkɹeɪzi", "fou", "", 860],
["daily", "ˈdeɪli", "quotidien", "", 861],
["paper", "ˈpeɪpɚ", "papier", "", 872],
["safe", "seɪf", "sûr", "", 876],
["waiting", "ˈweɪtɪŋ", "attendant", "", 898],
["ways", "weɪz", "façons", "", 899],
["base", "beɪs", "base", "", 902],
["created", "kɹiˈeɪtəd", "créé", "", 904],
["table", "ˈteɪbəl", "table", "", 916],
["cases", "ˈkeɪsəz", "cas", "", 923],
["straight", "stɹeɪt", "droit", "", 937],
["pain", "peɪn", "douleur", "", 953],
["places", "ˈpleɪsəz", "lieux", "", 955],
["create", "kɹiˈeɪt", "créer", "", 970],
["sales", "seɪlz", "ventes", "", 983],
["weight", "weɪt", "poids", "", 991],
["association", "əˌsoʊsiˈeɪʃən", "association", "", 995],
["is", "ɪz", "est", "atone : /z/ ; /s/ après consonne sourde", 8],
["been", "bɪn", "été", "atone : /bɪn/", 62],
["think", "θɪŋk", "penser", "", 89],
["really", "ˈɹɪli", "vraiment", "", 111],
["did", "dɪd", "a fait", "", 112],
["still", "stɪl", "encore", "", 125],
["little", "ˈlɪtəl", "petit", "", 167],
["things", "θɪŋz", "choses", "", 173],
["thing", "θɪŋ", "chose", "", 178],
["give", "ɡɪv", "donner", "", 179],
["big", "bɪɡ", "grand", "", 193],
["city", "ˈsɪti", "ville", "", 210],
["different", "ˈdɪfɚənt", "différent", "", 224],
["women", "ˈwɪmən", "femmes", "", 237],
["business", "ˈbɪznəs", "affaires", "", 238],
["system", "ˈsɪstəm", "système", "", 241],
["shit", "ʃɪt", "merde (vulg.)", "", 306],
["children", "ˈtʃɪldɹən", "enfants", "", 308],
["video", "ˈvɪdioʊ", "vidéo", "", 351],
["given", "ˈɡɪvən", "donné", "", 359],
["single", "ˈsɪŋɡəl", "seul", "", 367],
["history", "ˈhɪstɚi", "histoire", "", 384],
["win", "wɪn", "gagner", "", 394],
["pretty", "ˈpɹɪti", "joli", "", 402],
["bit", "bɪt", "morceau", "", 405],
["hit", "hɪt", "frapper", "", 407],
["million", "ˈmɪljən", "million", "", 452],
["minutes", "ˈmɪnəts", "minutes", "", 475],
["living", "ˈlɪvɪŋ", "vivant", "", 485],
["building", "ˈbɪldɪŋ", "bâtiment", "", 492],
["political", "pəˈlɪtəkəl", "politique", "", 498],
["kids", "kɪdz", "enfants", "", 510],
["list", "lɪst", "liste", "", 511],
["bring", "bɹɪŋ", "apporter", "", 517],
["thinking", "ˈθɪŋkɪŋ", "pensant", "", 558],
["issue", "ˈɪʃu", "problème", "", 567],
["killed", "kɪld", "tué", "", 583],
["miss", "mɪs", "manquer", "", 585],
["position", "pəˈzɪʃən", "position", "", 599],
["similar", "ˈsɪməlɚ", "similaire", "", 601],
["film", "fɪlm", "film", "", 607],
["military", "ˈmɪləˌtɛɹi", "militaire", "", 612],
["industry", "ˈɪndəstɹi", "industrie", "", 627],
["issues", "ˈɪʃuz", "problèmes", "", 629],
["middle", "ˈmɪdəl", "milieu", "", 648],
["wish", "wɪʃ", "souhait", "", 655],
["interest", "ˈɪntɹəst", "intérêt", "", 665],
["king", "kɪŋ", "roi", "", 667],
["original", "ɚˈɪdʒənəl", "original", "", 685],
["bill", "bɪl", "facture", "", 698],
["giving", "ˈɡɪvɪŋ", "donnant", "", 703],
["official", "əˈfɪʃəl", "officiel", "", 717],
["picture", "ˈpɪktʃɚ", "image", "", 743],
["decision", "dɪˈsɪʒən", "décision", "", 810],
["kill", "kɪl", "tuer", "", 815],
["written", "ˈɹɪtən", "écrit", "", 824],
["considered", "kənˈsɪdɚd", "considéré", "", 827],
["continue", "kənˈtɪnju", "continuer", "", 828],
["pick", "pɪk", "choisir", "", 843],
["simple", "ˈsɪmpəl", "simple", "", 848],
["simply", "ˈsɪmpli", "simplement", "", 849],
["built", "bɪlt", "construit", "", 857],
["difficult", "ˈdɪfəkəlt", "difficile", "", 865],
["figure", "ˈfɪɡjɚ", "chiffre", "", 866],
["systems", "ˈsɪstəmz", "systèmes", "", 878],
["internet", "ˈɪntɚˌnɛt", "internet", "", 889],
["listen", "ˈlɪsən", "écouter", "", 890],
["missing", "ˈmɪsɪŋ", "manquant", "", 908],
["risk", "ɹɪsk", "risque", "", 913],
["build", "bɪld", "construire", "", 921],
["district", "ˈdɪstɹɪkt", "district", "", 925],
["minister", "ˈmɪnəstɚ", "ministre", "", 930],
["visit", "ˈvɪzɪt", "visiter", "", 938],
["gives", "ɡɪvz", "donne", "", 948],
["river", "ˈɹɪvɚ", "rivière", "", 958],
["specific", "spəˈsɪfɪk", "spécifique", "", 962],
["limited", "ˈlɪmətəd", "limité", "", 976],
["addition", "əˈdɪʃən", "ajout", "", 992],
["have", "hæv", "avoir", "atone : /həv/, /əv/", 20],
["has", "hæz", "a", "atone : /həz/, /əz/", 47],
["had", "hæd", "avait", "atone : /həd/, /əd/", 54],
["back", "bæk", "dos", "", 93],
["last", "læst", "dernier", "", 138],
["man", "mæn", "homme", "", 144],
["am", "æm", "suis", "atone : /əm/, /m̩/", 155],
["family", "ˈfæməli", "famille", "", 198],
["having", "ˈhævɪŋ", "ayant", "", 225],
["bad", "bæd", "mauvais", "", 261],
["national", "ˈnæʃənəl", "national", "", 281],
["actually", "ˈækˌtʃuəli", "en fait", "", 293],
["thank", "θæŋk", "remercier", "", 307],
["black", "blæk", "noir", "", 316],
["fact", "fækt", "fait", "", 358],
["half", "hæf", "moitié", "", 361],
["hand", "hænd", "main", "", 362],
["matter", "ˈmætɚ", "matière", "", 401],
["understand", "ˌʌndɚˈstænd", "comprendre", "", 413],
["class", "klæs", "classe", "", 416],
["international", "ˌɪntɚˈnæʃənəl", "international", "", 421],
["past", "pæst", "passé", "", 423],
["happy", "ˈhæpi", "heureux", "", 428],
["ask", "æsk", "demander", "", 437],
["rather", "ˈɹæðɚ", "plutôt", "", 461],
["act", "ækt", "agir", "", 479],
["asked", "æskt", "demandé", "", 481],
["plan", "plæn", "plan", "", 497],
["example", "ɪɡˈzæmpəl", "exemple", "", 520],
["chance", "tʃæns", "chance", "", 528],
["action", "ˈækʃən", "action", "", 537],
["land", "lænd", "terre", "", 584],
["happened", "ˈhæpənd", "arrivé", "", 608],
["happen", "ˈhæpən", "arriver", "", 625],
["answer", "ˈænsɚ", "répondre", "", 657],
["added", "ˈædəd", "ajouté", "", 671],
["average", "ˈævɚɪdʒ", "moyenne", "", 673],
["bank", "bæŋk", "banque", "", 674],
["hands", "hændz", "mains", "", 679],
["exactly", "ɪɡˈzæktli", "exactement", "", 702],
["value", "ˈvælju", "valeur", "", 713],
["stand", "stænd", "se tenir debout", "", 723],
["tax", "tæks", "impôt", "", 725],
["fast", "fæst", "rapide", "", 734],
["management", "ˈmænədʒmənt", "gestion", "", 740],
["match", "mætʃ", "match", "", 741],
["natural", "ˈnætʃɚəl", "naturel", "", 777],
["language", "ˈlæŋɡwədʒ", "langue", "", 794],
["add", "æd", "ajouter", "", 803],
["attack", "əˈtæk", "attaque", "", 805],
["perhaps", "pɚˈhæps", "peut-être", "", 817],
["financial", "fəˈnænʃəl", "financier", "", 836],
["staff", "stæf", "personnel", "", 850],
["began", "bɪˈɡæn", "a commencé", "", 856],
["practice", "ˈpɹæktəs", "pratique", "", 892],
["access", "ˈækˌsɛs", "accès", "", 900],
["pass", "pæs", "passer", "", 910],
["fans", "fænz", "fans", "", 946],
["standard", "ˈstændɚd", "standard", "", 963],
["album", "ˈælbəm", "album", "", 966],
["track", "tɹæk", "piste", "", 988],
["capital", "ˈkæpətəl", "capitale", "", 998],
["like", "laɪk", "aimer", "", 42],
["time", "taɪm", "temps", "", 60],
["right", "ɹaɪt", "droit", "", 113],
["why", "waɪ", "pourquoi", "", 123],
["life", "laɪf", "vie", "", 131],
["find", "faɪnd", "trouver", "", 164],
["high", "haɪ", "haut", "", 166],
["night", "naɪt", "nuit", "", 214],
["times", "taɪmz", "fois", "", 242],
["white", "waɪt", "blanc", "", 284],
["side", "saɪd", "côté", "", 288],
["try", "tɹaɪ", "essayer", "", 290],
["line", "laɪn", "ligne", "", 297],
["trying", "ˈtɹaɪɪŋ", "essayant", "", 312],
["united", "juˈnaɪtɪd", "uni", "", 313],
["kind", "kaɪnd", "genre", "", 326],
["guys", "ɡaɪz", "les gars", "", 360],
["mind", "maɪnd", "esprit", "", 365],
["guy", "ɡaɪ", "gars", "", 374],
["nice", "naɪs", "gentil", "", 409],
["light", "laɪt", "lumière", "", 450],
["buy", "baɪ", "acheter", "", 459],
["child", "tʃaɪld", "enfant", "", 482],
["fire", "ˈfaɪɚ", "feu", "", 483],
["quite", "kwaɪt", "assez", "", 499],
["final", "ˈfaɪnəl", "final", "", 507],
["sometimes", "səmˈtaɪmz", "parfois", "", 513],
["type", "taɪp", "type", "", 526],
["fight", "faɪt", "se battre", "", 563],
["fine", "faɪn", "bien", "", 564],
["price", "pɹaɪs", "prix", "", 570],
["wife", "waɪf", "épouse", "", 578],
["site", "saɪt", "site", "", 589],
["eyes", "aɪz", "yeux", "", 594],
["died", "daɪd", "mort", "", 606],
["likely", "ˈlaɪkli", "probable", "", 611],
["inside", "ˌɪnˈsaɪd", "à l'intérieur", "", 628],
["private", "ˈpɹaɪvət", "privé", "", 632],
["rights", "ɹaɪts", "droits", "", 635],
["higher", "ˈhaɪɚ", "plus haut", "", 645],
["design", "dɪˈzaɪn", "design", "", 659],
["finally", "ˈfaɪnəli", "finalement", "", 660],
["society", "səˈsaɪəti", "société", "", 670],
["tried", "tɹaɪd", "essayé", "", 693],
["provide", "pɹəˈvaɪd", "fournir", "", 706],
["drive", "dɹaɪv", "conduire", "", 731],
["size", "saɪz", "taille", "", 744],
["science", "ˈsaɪəns", "science", "", 760],
["style", "staɪl", "style", "", 782],
["title", "ˈtaɪtəl", "titre", "", 802],
["decided", "ˌdɪˈsaɪdɪd", "décidé", "", 809],
["entire", "ɪnˈtaɪɚ", "entier", "", 812],
["sign", "saɪn", "signe", "", 847],
["die", "daɪ", "mourir", "", 864],
["writing", "ˈɹaɪtɪŋ", "écriture", "", 882],
["tonight", "təˈnaɪt", "ce soir", "", 964],
["write", "ɹaɪt", "écrire", "", 965],
["eye", "aɪ", "œil", "", 974],
["provided", "pɹəˈvaɪdɪd", "fourni", "", 980],
["required", "ɹiˈkwaɪɚd", "requis", "", 982],
["be", "bi", "être", "", 17],
["people", "ˈpipəl", "gens", "", 66],
["see", "si", "voir", "", 85],
["even", "ˈivɪn", "même", "", 106],
["need", "nid", "avoir besoin", "", 110],
["being", "ˈbiɪŋ", "étant", "", 117],
["each", "itʃ", "chaque", "", 185],
["feel", "fil", "sentir", "", 194],
["team", "tim", "équipe", "", 196],
["keep", "kip", "garder", "", 199],
["please", "pliz", "s'il vous plaît", "", 201],
["free", "fɹi", "libre", "", 204],
["real", "ɹil", "réel", "", 222],
["week", "wik", "semaine", "", 243],
["mean", "min", "signifier", "", 265],
["seen", "sin", "vu", "", 272],
["believe", "bɪˈliv", "croire", "", 277],
["season", "ˈsizən", "saison", "", 305],
["least", "list", "le moins", "", 337],
["means", "minz", "moyen", "", 338],
["needs", "nidz", "besoins", "", 408],
["idea", "aɪˈdiə", "idée", "", 420],
["leave", "liv", "partir", "", 441],
["police", "pəˈlis", "police", "", 454],
["deal", "dil", "affaire", "", 460],
["reason", "ˈɹizən", "raison", "", 462],
["media", "ˈmidiə", "médias", "", 487],
["easy", "ˈizi", "facile", "", 493],
["street", "stɹit", "rue", "", 515],
["meet", "mit", "rencontrer", "", 524],
["field", "fild", "champ", "", 550],
["seems", "simz", "semble", "", 557],
["weeks", "wiks", "semaines", "", 640],
["needed", "ˈnidəd", "nécessaire", "", 649],
["east", "ist", "est", "", 678],
["received", "ɹəˈsivd", "reçu", "", 689],
["meeting", "ˈmitɪŋ", "réunion", "", 705],
["reading", "ˈɹidɪŋ", "lecture", "", 720],
["eat", "it", "manger", "", 732],
["feeling", "ˈfilɪŋ", "sentiment", "", 736],
["green", "ɡɹin", "vert", "", 738],
["league", "liɡ", "ligue", "", 739],
["key", "ki", "clé", "", 754],
["chief", "tʃif", "chef", "", 768],
["complete", "kəmˈplit", "complet", "", 788],
["release", "ɹiˈlis", "libérer", "", 819],
["legal", "ˈliɡəl", "légal", "", 840],
["seem", "sim", "sembler", "", 845],
["sea", "si", "mer", "", 894],
["deep", "dip", "profond", "", 905],
["released", "ɹiˈlist", "sorti", "", 912],
["sleep", "slip", "dormir", "", 915],
["piece", "pis", "morceau", "", 933],
["recent", "ˈɹisənt", "récent", "", 935],
["seeing", "ˈsiɪŋ", "voyant", "", 936],
["speak", "spik", "parler", "", 961],
["peace", "pis", "paix", "", 979],
["recently", "ˈɹisəntli", "récemment", "", 981],
["beat", "bit", "battre", "", 996],
["just", "dʒʌst", "juste", "", 41],
["up", "ʌp", "en haut", "", 44],
["some", "sʌm", "quelques", "atone : /səm/", 69],
["other", "ˈʌðɚ", "autre", "", 73],
["much", "mʌtʃ", "beaucoup", "", 103],
["such", "sʌtʃ", "tel", "", 142],
["love", "lʌv", "amour", "", 143],
["come", "kʌm", "venir", "", 156],
["another", "əˈnʌðɚ", "un autre", "", 170],
["money", "ˈmʌni", "argent", "", 203],
["number", "ˈnʌmbɚ", "nombre", "", 209],
["company", "ˈkʌmpəˌni", "entreprise", "", 217],
["done", "dʌn", "fait", "", 228],
["government", "ˈɡʌvɚmənt", "gouvernement", "", 232],
["public", "ˈpʌblɪk", "public", "", 235],
["enough", "ɪˈnʌf", "assez", "", 251],
["once", "wʌns", "une fois", "", 266],
["run", "ɹʌn", "courir", "", 300],
["country", "ˈkʌntɹi", "pays", "", 303],
["young", "jʌŋ", "jeune", "", 352],
["become", "bɪˈkʌm", "devenir", "", 368],
["coming", "ˈkʌmɪŋ", "venant", "", 370],
["comes", "kʌmz", "vient", "", 418],
["months", "mʌnθs", "mois", "", 431],
["fucking", "ˈfʌkɪŋ", "putain de (vulg.)", "", 448],
["fun", "fʌn", "amusement", "", 484],
["front", "fɹʌnt", "devant", "", 509],
["son", "sʌn", "fils", "", 514],
["study", "ˈstʌdi", "étudier", "", 534],
["month", "mʌnθ", "mois", "", 542],
["cut", "kʌt", "couper", "", 549],
["mother", "ˈmʌðɚ", "mère", "", 555],
["results", "ɹɪˈzʌlts", "résultats", "", 572],
["running", "ˈɹʌnɪŋ", "courant", "", 573],
["summer", "ˈsʌmɚ", "été", "", 576],
["club", "klʌb", "club", "", 604],
["won", "wʌn", "gagné", "", 618],
["couple", "ˈkʌpəl", "couple", "", 622],
["companies", "ˈkʌmpəˌniz", "entreprises", "", 643],
["result", "ɹɪˈzʌlt", "résultat", "", 651],
["production", "pɹəˈdʌkʃən", "production", "", 718],
["stuff", "stʌf", "truc", "", 724],
["countries", "ˈkʌntɹiz", "pays", "", 729],
["trust", "tɹʌst", "confiance", "", 746],
["brother", "ˈbɹʌðɚ", "frère", "", 765],
["cup", "kʌp", "tasse", "", 769],
["blood", "blʌd", "sang", "", 786],
["cover", "ˈkʌvɚ", "couvrir", "", 830],
["published", "ˈpʌblɪʃt", "publié", "", 875],
["culture", "ˈkʌltʃɚ", "culture", "", 945],
["funny", "ˈfʌni", "drôle", "", 975],
["so", "soʊ", "donc", "", 33],
["no", "noʊ", "non", "", 51],
["only", "ˈoʊnli", "seulement", "", 79],
["know", "noʊ", "savoir", "", 84],
["go", "ɡoʊ", "aller", "", 98],
["most", "moʊst", "le plus", "", 102],
["going", "ˈɡoʊɪŋ", "allant", "", 120],
["home", "hoʊm", "maison", "", 145],
["both", "boʊθ", "les deux", "", 153],
["old", "oʊld", "vieux", "", 168],
["own", "oʊn", "propre", "", 172],
["show", "ʃoʊ", "montrer", "", 192],
["told", "toʊld", "dit", "", 259],
["open", "ˈoʊpən", "ouvrir", "", 304],
["whole", "hoʊl", "entier", "", 322],
["hope", "hoʊp", "espoir", "", 335],
["local", "ˈloʊkəl", "local", "", 347],
["post", "poʊst", "publication", "", 349],
["ago", "əˈɡoʊ", "il y a", "", 353],
["social", "ˈsoʊʃəl", "social", "", 355],
["control", "kənˈtɹoʊl", "contrôle", "", 371],
["known", "noʊn", "connu", "", 385],
["low", "loʊ", "bas", "", 451],
["phone", "foʊn", "téléphone", "", 488],
["program", "ˈpɹoʊˌɡɹæm", "programme", "", 525],
["moment", "ˈmoʊmənt", "moment", "", 554],
["road", "ɹoʊd", "route", "", 556],
["shows", "ʃoʊz", "montre", "", 574],
["goes", "ɡoʊz", "va", "", 582],
["total", "ˈtoʊtəl", "total", "", 602],
["hold", "hoʊld", "tenir", "", 626],
["gold", "ɡoʊld", "or", "", 662],
["alone", "əˈloʊn", "seul", "", 672],
["role", "ɹoʊl", "rôle", "", 690],
["lower", "ˈloʊɚ", "plus bas", "", 776],
["vote", "voʊt", "vote", "", 783],
["code", "koʊd", "code", "", 826],
["knows", "noʊz", "sait", "", 868],
["goal", "ɡoʊl", "but", "", 887],
["note", "noʊt", "note", "", 931],
["wrote", "ɹoʊt", "a écrit", "", 942],
["growth", "ɡɹoʊθ", "croissance", "", 949],
["cold", "koʊld", "froid", "", 969],
["was", "wɑz", "était", "atone : /wəz/", 16],
["not", "nɑt", "ne…pas", "atone : /nt/ dans les contractions", 23],
["want", "wɑnt", "vouloir", "", 96],
["got", "ɡɑt", "obtenu", "", 127],
["lot", "lɑt", "beaucoup", "", 212],
["top", "tɑp", "haut", "", 236],
["stop", "stɑp", "arrêter", "", 274],
["job", "dʒɑb", "emploi", "", 287],
["following", "ˈfɑloʊɪŋ", "suivant", "", 317],
["body", "ˈbɑdi", "corps", "", 369],
["problem", "ˈpɹɑbləm", "problème", "", 378],
["probably", "ˈpɹɑbəˌbli", "probablement", "", 411],
["possible", "ˈpɑsəbəl", "possible", "", 424],
["cause", "kɑz", "cause", "", 426],
["watch", "wɑtʃ", "regarder", "", 445],
["college", "ˈkɑlɪdʒ", "université", "", 518],
["father", "ˈfɑðɚ", "père", "", 529],
["process", "ˈpɹɑˌsɛs", "processus", "", 531],
["cost", "kɑst", "coûter", "", 548],
["wants", "wɑnts", "veut", "", 560],
["shot", "ʃɑt", "tir", "", 588],
["common", "ˈkɑmən", "commun", "", 605],
["problems", "ˈpɹɑbləmz", "problèmes", "", 633],
["policy", "ˈpɑləsi", "politique", "", 669],
["hot", "hɑt", "chaud", "", 680],
["follow", "ˈfɑloʊ", "suivre", "", 715],
["model", "ˈmɑdəl", "modèle", "", 742],
["mom", "mɑm", "maman", "", 755],
["property", "ˈpɹɑpɚti", "propriété", "", 779],
["quality", "ˈkwɑləti", "qualité", "", 780],
["economic", "ˌɛkəˈnɑmɪk", "économique", "", 790],
["involved", "ˌɪnˈvɑlvd", "impliqué", "", 792],
["technology", "tɛkˈnɑlədʒi", "technologie", "", 821],
["hospital", "ˈhɑˌspɪtəl", "hôpital", "", 867],
["modern", "ˈmɑdɚn", "moderne", "", 870],
["popular", "ˈpɑpjəlɚ", "populaire", "", 874],
["followed", "ˈfɑloʊd", "suivi", "", 906],
["box", "bɑks", "boîte", "", 920],
["products", "ˈpɹɑdəkts", "produits", "", 934],
["response", "ɹɪˈspɑns", "réponse", "", 957],
["rock", "ɹɑk", "rocher", "", 959],
["tomorrow", "təˈmɑˌɹoʊ", "demain", "", 987],
["watching", "ˈwɑtʃɪŋ", "regardant", "", 990],
["do", "du", "faire", "atone : /də/ ; /du/ devant voyelle", 50],
["new", "nu", "nouveau", "", 65],
["too", "tu", "trop", "", 119],
["used", "juzd", "utilisé", "", 152],
["school", "skul", "école", "", 182],
["doing", "ˈduɪŋ", "faisant", "", 218],
["few", "fju", "peu de", "", 219],
["group", "ɡɹup", "groupe", "", 233],
["music", "ˈmjuzɪk", "musique", "", 270],
["using", "ˈjuzɪŋ", "utilisant", "", 314],
["news", "nuz", "nouvelles", "", 339],
["food", "fud", "nourriture", "", 373],
["true", "tɹu", "vrai", "", 380],
["room", "ɹum", "pièce", "", 389],
["due", "du", "dû", "", 427],
["human", "ˈhjumən", "humain", "", 429],
["move", "muv", "bouger", "", 432],
["community", "kəˈmjunəti", "communauté", "", 438],
["future", "ˈfjutʃɚ", "futur", "", 449],
["soon", "sun", "bientôt", "", 465],
["students", "ˈstudənts", "étudiants", "", 545],
["beautiful", "ˈbjutəfəl", "beau", "", 580],
["include", "ˌɪnˈklud", "inclure", "", 595],
["knew", "nu", "savait", "", 609],
["view", "vju", "vue", "", 639],
["movie", "ˈmuvi", "film", "", 684],
["cool", "kul", "frais", "", 700],
["usually", "ˈjuʒəwəli", "habituellement", "", 712],
["blue", "blu", "bleu", "", 728],
["groups", "ɡɹups", "groupes", "", 752],
["review", "ˌɹiˈvju", "critique", "", 759],
["poor", "puɹ", "pauvre", "", 818],
["lose", "luz", "perdre", "", 841],
["super", "ˈsupɚ", "super", "", 851],
["union", "ˈjunjən", "union", "", 852],
["huge", "hjudʒ", "énorme", "", 888],
["rules", "ɹulz", "règles", "", 893],
["schools", "skulz", "écoles", "", 914],
["truth", "tɹuθ", "vérité", "", 918],
["included", "ˌɪnˈkludəd", "inclus", "", 950],
["moving", "ˈmuvɪŋ", "émouvant", "", 977],
["student", "ˈstudənt", "étudiant", "", 986],
["all", "ɔl", "tout", "", 32],
["also", "ˈɔlsoʊ", "aussi", "", 70],
["off", "ɔf", "hors", "", 122],
["long", "lɔŋ", "long", "", 146],
["always", "ˈɔlˌweɪz", "toujours", "", 162],
["called", "kɔld", "appelé", "", 223],
["thought", "θɔt", "pensée", "", 227],
["water", "ˈwɔtɚ", "eau", "", 275],
["call", "kɔl", "appeler", "", 278],
["small", "smɔl", "petit", "", 282],
["law", "lɔ", "loi", "", 318],
["talk", "tɔk", "parler", "", 356],
["often", "ˈɔfən", "souvent", "", 366],
["office", "ˈɔfɪs", "bureau", "", 376],
["almost", "ˈɔlˌmoʊst", "presque", "", 382],
["lost", "lɔst", "perdu", "", 387],
["wrong", "ɹɔŋ", "faux", "", 395],
["wanted", "ˈwɔntɪd", "voulu", "", 425],
["saw", "sɔ", "a vu", "", 443],
["talking", "ˈtɔkɪŋ", "parlant", "", 501],
["song", "sɔŋ", "chanson", "", 533],
["strong", "stɹɔŋ", "fort", "", 590],
["online", "ˈɔnˌlaɪn", "en ligne", "", 630],
["gone", "ɡɔn", "parti", "", 663],
["brought", "bɹɔt", "apporté", "", 675],
["longer", "ˈlɔŋɡɚ", "plus long", "", 682],
["fall", "fɔl", "tomber", "", 733],
["dog", "dɔɡ", "chien", "", 789],
["walk", "wɔk", "marcher", "", 853],
["daughter", "ˈdɔtɚ", "fille", "", 862],
["loss", "lɔs", "perte", "", 869],
["offer", "ˈɔfɚ", "offrir", "", 909],
["ball", "bɔl", "balle", "", 919],
["wall", "wɔl", "mur", "", 939],
["officer", "ˈɔfəsɚ", "officier", "", 952],
["were", "wɝ", "étaient", "atone : /wɚ/", 52],
["first", "fɝst", "premier", "", 81],
["work", "wɝk", "travail", "", 114],
["world", "wɝld", "monde", "", 133],
["person", "ˈpɝsən", "personne", "", 248],
["service", "ˈsɝvəs", "service", "", 302],
["working", "ˈwɝkɪŋ", "travaillant", "", 331],
["early", "ˈɝli", "tôt", "", 343],
["university", "ˌjunəˈvɝsəti", "université", "", 393],
["girl", "ɡɝl", "fille", "", 399],
["turn", "tɝn", "tourner", "", 467],
["further", "ˈfɝðɚ", "plus loin", "", 473],
["services", "ˈsɝvəsəz", "services", "", 477],
["works", "wɝks", "travaille", "", 503],
["current", "ˈkɝənt", "actuel", "", 519],
["heard", "hɝd", "entendu", "", 522],
["word", "wɝd", "mot", "", 535],
["words", "wɝdz", "mots", "", 546],
["term", "tɝm", "terme", "", 577],
["personal", "ˈpɝsɪnəl", "personnel", "", 614],
["return", "ɹɪˈtɝn", "retourner", "", 634],
["girls", "ɡɝlz", "filles", "", 661],
["learn", "lɝn", "apprendre", "", 668],
["certain", "ˈsɝtən", "certain", "", 676],
["church", "tʃɝtʃ", "église", "", 677],
["worked", "wɝkt", "travaillé", "", 694],
["worth", "wɝθ", "valeur", "", 695],
["terms", "tɝmz", "termes", "", 801],
["turned", "tɝnd", "tourné", "", 822],
["currently", "ˈkɝəntli", "actuellement", "", 831],
["version", "ˈvɝʒən", "version", "", 879],
["earth", "ɝθ", "terre", "", 885],
["sir", "sɝ", "monsieur", "", 895],
["there", "ðɛɹ", "là", "atone : /ðɚ/ dans there is", 57],
["very", "ˈvɛɹi", "très", "", 104],
["where", "wɛɹ", "où", "", 105],
["here", "hiɹ", "ici", "", 109],
["year", "jɪɹ", "année", "", 115],
["years", "jɪɹz", "années", "", 116],
["sure", "ʃʊɹ", "sûr", "", 195],
["care", "kɛɹ", "soin", "", 239],
["area", "ˈɛɹiə", "zone", "", 315],
["air", "ɛɹ", "air", "", 404],
["series", "ˈsɪɹiz", "série", "", 434],
["experience", "ɪkˈspɪɹiəns", "expérience", "", 521],
["clear", "klɪɹ", "clair", "", 538],
["hear", "hiɹ", "entendre", "", 566],
["parents", "ˈpɛɹənts", "parents", "", 597],
["period", "ˈpɪɹiəd", "période", "", 598],
["security", "sɪˈkjʊɹəti", "sécurité", "", 615],
["share", "ʃɛɹ", "partager", "", 616],
["areas", "ˈɛɹiəz", "zones", "", 696],
["various", "ˈvɛɹiəs", "divers", "", 763],
["character", "ˈkɛɹɪktɚ", "personnage", "", 767],
["serious", "ˈsɪɹiəs", "sérieux", "", 799],
["hair", "hɛɹ", "cheveux", "", 838],
["career", "kɚˈɪɹ", "carrière", "", 858],
["married", "ˈmɛɹid", "marié", "", 951],
["are", "ɑɹ", "sont", "atone : /ɚ/", 19],
["part", "pɑɹt", "partie", "", 157],
["start", "stɑɹt", "commencer", "", 240],
["hard", "hɑɹd", "dur", "", 264],
["far", "fɑɹ", "loin", "", 286],
["party", "ˈpɑɹti", "fête", "", 299],
["car", "kɑɹ", "voiture", "", 323],
["large", "lɑɹdʒ", "grand", "", 386],
["started", "ˈstɑɹtɪd", "commencé", "", 391],
["heart", "hɑɹt", "cœur", "", 474],
["art", "ɑɹt", "art", "", 490],
["market", "ˈmɑɹkət", "marché", "", 495],
["department", "dɪˈpɑɹtmənt", "service", "", 561],
["star", "stɑɹ", "étoile", "", 637],
["sorry", "ˈsɑɹi", "désolé", "", 652],
["park", "pɑɹk", "parc", "", 686],
["article", "ˈɑɹtəkəl", "article", "", 804],
["parts", "pɑɹts", "parties", "", 873],
["starting", "ˈstɑɹtɪŋ", "commençant", "", 877],
["army", "ˈɑɹmi", "armée", "", 883],
["mark", "mɑɹk", "marque", "", 907],
["card", "kɑɹd", "carte", "", 922],
["dark", "dɑɹk", "sombre", "", 924],
["charge", "tʃɑɹdʒ", "frais", "", 968],
["more", "mɔɹ", "plus", "", 49],
["support", "səˈpɔɹt", "soutenir", "", 267],
["order", "ˈɔɹdɚ", "ordre", "", 298],
["war", "wɔɹ", "guerre", "", 321],
["story", "ˈstɔɹi", "histoire", "", 330],
["course", "kɔɹs", "cours", "", 332],
["important", "ˌɪmˈpɔɹtənt", "important", "", 336],
["court", "kɔɹt", "tribunal", "", 357],
["north", "nɔɹθ", "nord", "", 442],
["morning", "ˈmɔɹnɪŋ", "matin", "", 453],
["short", "ʃɔɹt", "court", "", 455],
["report", "ɹiˈpɔɹt", "rapport", "", 464],
["form", "fɔɹm", "forme", "", 472],
["former", "ˈfɔɹmɚ", "ancien", "", 508],
["board", "bɔɹd", "tableau", "", 547],
["force", "fɔɹs", "force", "", 565],
["performance", "pɚˈfɔɹməns", "performance", "", 687],
["source", "sɔɹs", "source", "", 711],
["forward", "ˈfɔɹwɚd", "en avant", "", 751],
["lord", "lɔɹd", "seigneur", "", 795],
["born", "bɔɹn", "né", "", 806],
["door", "dɔɹ", "porte", "", 832],
["foreign", "ˈfɔɹən", "étranger", "", 837],
["store", "stɔɹ", "magasin", "", 985],
["out", "aʊt", "dehors", "", 45],
["how", "haʊ", "comment", "", 67],
["now", "naʊ", "maintenant", "", 72],
["down", "daʊn", "en bas", "", 134],
["found", "faʊnd", "trouvé", "", 190],
["power", "ˈpaʊɚ", "pouvoir", "", 271],
["hours", "ˈaʊɚz", "heures", "", 375],
["south", "saʊθ", "sud", "", 379],
["outside", "ˈaʊtˈsaɪd", "dehors", "", 543],
["town", "taʊn", "ville", "", 559],
["account", "əˈkaʊnt", "compte", "", 592],
["county", "ˈkaʊnti", "comté", "", 621],
["hour", "ˈaʊɚ", "heure", "", 646],
["ground", "ɡɹaʊnd", "sol", "", 704],
["sound", "saʊnd", "son", "", 710],
["round", "ɹaʊnd", "rond", "", 721],
["amount", "əˈmaʊnt", "quantité", "", 727],
["council", "ˈkaʊnsəl", "conseil", "", 829],
["allowed", "əˈlaʊd", "permis", "", 943],
["allow", "əˈlaʊ", "permettre", "", 994],
["brown", "bɹaʊn", "marron", "", 997],
["good", "ɡʊd", "bon", "", 78],
["look", "lʊk", "regarder", "", 147],
["put", "pʊt", "mettre", "", 202],
["looking", "ˈlʊkɪŋ", "regardant", "", 234],
["full", "fʊl", "plein", "", 253],
["point", "pɔɪnt", "point", "", 256],
["took", "tʊk", "a pris", "", 283],
["book", "bʊk", "livre", "", 342],
["looks", "lʊks", "regarde", "", 422],
["woman", "ˈwʊmən", "femme", "", 436],
["points", "pɔɪnts", "points", "", 569],
["boy", "bɔɪ", "garçon", "", 658],
["books", "bʊks", "livres", "", 699],
["football", "ˈfʊtˌbɔl", "football américain", "", 770],
["looked", "lʊkt", "regardé", "", 775],
["oil", "ɔɪl", "huile", "", 797],
["enjoy", "ˌɛnˈdʒɔɪ", "apprécier", "", 811],
["choice", "tʃɔɪs", "choix", "", 825],
["voice", "vɔɪs", "voix", "", 880],
["boys", "bɔɪz", "garçons", "", 944],
["God", "ɡɑd", "Dieu", "", 231],
["American", "əˈmɛɹəkən", "américain", "", 294],
["John", "dʒɑn", "Jean", "prénom", 400],
["York", "jɔɹk", "York", "New York", 415],
["London", "ˈlʌndən", "Londres", "Londres", 523],
["March", "mɑɹtʃ", "mars", "", 530],
["America", "əˈmɛɹəkə", "Amérique", "Amérique", 579],
["June", "dʒun", "juin", "", 596],
["April", "ˈeɪpɹəl", "avril", "", 619],
["English", "ˈɪŋɡlɪʃ", "anglais", "", 624],
["British", "ˈbɹɪtɪʃ", "britannique", "", 642],
["July", "ˌdʒuˈlaɪ", "juillet", "", 666],
["September", "sɛpˈtɛmbɚ", "septembre", "", 709],
["David", "ˈdeɪvɪd", "David", "prénom", 730],
["England", "ˈɪŋɡlənd", "Angleterre", "", 750],
["James", "dʒeɪmz", "Jacques", "prénom", 773],
["October", "ɑkˈtoʊbɚ", "octobre", "", 778],
["August", "ˈɑɡəst", "août", "", 785],
["China", "ˈtʃaɪnə", "Chine", "", 787],
["November", "noʊˈvɛmbɚ", "novembre", "", 796],
["French", "fɹɛntʃ", "français", "", 813],
["January", "ˈdʒænjuˌɛɹi", "janvier", "", 814],
["European", "ˌjʊɹəˈpiən", "européen", "", 834],
["Michael", "ˈmaɪkəl", "Michel", "prénom", 842],
["Washington", "ˈwɑʃɪŋtən", "Washington", "capitale des États-Unis", 854],
["December", "dɪˈsɛmbɚ", "décembre", "", 863],
["Australia", "ɔˈstɹeɪljə", "Australie", "", 884],
["Europe", "ˈjʊɹəp", "Europe", "", 926],
["George", "dʒɔɹdʒ", "Georges", "prénom", 927],
["India", "ˈɪndiə", "Inde", "", 928],
["February", "ˈfɛbjəˌwɛɹi", "février", "", 947],
["Paul", "pɔl", "Paul", "prénom", 954],
["Chinese", "tʃaɪˈniz", "chinois", "", 999]
];

var G = [
["Prépositions", 38],
["Pronoms et articles", 39],
["Contractions et interjections", 37],
["Conjonctions, auxiliaires, modaux, numéraux et possessifs", 38],
["Prononciation variable", 14],
["/ɛ/ — Partie 1", 31],
["/ɛ/ — Partie 2", 31],
["/ɛ/ — Partie 3", 32],
["/eɪ/ — Partie 1", 28],
["/eɪ/ — Partie 2", 29],
["/eɪ/ — Partie 3", 29],
["/ɪ/ — Partie 1", 26],
["/ɪ/ — Partie 2", 26],
["/ɪ/ — Partie 3", 26],
["/æ/ — Partie 1", 31],
["/æ/ — Partie 2", 31],
["/aɪ/ — Partie 1", 30],
["/aɪ/ — Partie 2", 30],
["/i/ — Partie 1", 29],
["/i/ — Partie 2", 30],
["/ʌ/ — Partie 1", 25],
["/ʌ/ — Partie 2", 26],
["/oʊ/ — Partie 1", 21],
["/oʊ/ — Partie 2", 22],
["/ɑ/ — Partie 1", 21],
["/ɑ/ — Partie 2", 22],
["/u/ — Partie 1", 21],
["/u/ — Partie 2", 21],
["/ɔ/", 35],
["/ɝ/", 33],
["/ɛɹ, ɪɹ, iɹ, ʊɹ/", 25],
["/ɑɹ/", 24],
["/ɔɹ/", 24],
["/aʊ/", 21],
["/ʊ, ɔɪ/", 20],
["Noms propres", 33]
];
